# Generated by Django 3.0.8 on 2020-07-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
